endpoints:
  - name: Wikipedie
#    url: https://fr.wikipedia.org
    url: https://fr.wikipediafail.org
    method: GET
    header:
      SOME-HEADER: SOME-VALUE
    timeout: 1 # seconds
    expectation:
      - type: HTTP_STATUS
        status_range: 200-205
      - type: LATENCY
        threshold: 0.3
    allowed_fails: 0
    component_id: 1
    metric_id: 1
    action:
      - UPDATE_STATUS
      - CREATE_INCIDENT
      - PUSH_METRICS
    public_incidents: true
    latency_unit: ms
    frequency: 60 # in seconds
cachet:
#  api_url: http://172.0.3.2:8000/api/v1
  api_url: http://cachet:8000/api/v1
  token:
    - type: TOKEN
      value: jqu4pVHLuCsFu4qFLyZQ
#    - type: ENVIRONMENT_VARIABLE
#      value: CACHET_TOKEN
#    - type: AWS_SECRETS_MANAGER
#      secret_name: cachethq
#      secret_key: token
#      region: us-west-2
